services:
  web:
    build: ./apache
    container_name: iwasakipos_web
    tty: true
    ports:
      - "8080:80"
    environment:
      - LOGIN_ENABLED=${LOGIN_ENABLED}
      - LOGIN_USER=${LOGIN_USER}
      - LOGIN_PASSWORD=${LOGIN_PASSWORD}
      - AUTH_FILE_PATH=${AUTH_FILE_PATH}
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    command: > 
      bash -c "composer install && chmod 777 /var/www/html/setting.json "
    entrypoint: ["/usr/local/bin/init.sh"]


  db:
    build: ./mariaDB
    container_name: iwasakipos_db
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
      LC_ALL: "C.UTF-8"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
